# Generated by Django 5.1.6 on 2025-05-14 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaboration', '0002_alter_group_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Subitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('weight', models.IntegerField(default=1)),
                ('completion_status', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.item')),
            ],
            options={
                'verbose_name': 'Subitem',
                'verbose_name_plural': 'Subitems',
                'db_table': 'Subitem',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaboration.group')),
            ],
            options={
                'verbose_name': 'Workspace/Checklist',
                'verbose_name_plural': 'Workspaces/Checklists',
                'db_table': 'Workspace',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.workspace'),
        ),
    ]
