# Generated by Django 5.1.6 on 2025-04-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
